python3 train.py --model Condition \
    --epochs 20 \
    --batch 128 \
    --imgsz 224 \
    --data_path ./data/fashion-dataset/images \
    --csv_train ./data/fashion_product_train.csv \
    --csv_val ./data/fashion_product_validation.csv \
    --csv_test ./data/fashion_product_test.csv \
    --master_column masterCategory \
    --sub_column subCategory \
    --article_column articleType \
    --filepath_column filepath